global:
  scrape_intervals: 15s
 scrape_configs: 
    - job_name: "prometheus"
      static_configs:
         - targets: ["localhost:9090"]
    - job_name: "cadvisor"
      static_configs:
        - targets: ["observability-cadvisor-1:8080"]
        
